-- ==========================================================================
--  ESQUEMA DE BASE DE DATOS — APP DE CLUB CON SISTEMA DE TOKENS
--  Archivo: 03_ESQUEMA_BD.sql
--  Para: Supabase (PostgreSQL) — pegar entero en el SQL Editor y ejecutar.
--
--  Cubre LOS DOS PANELES: socios.html y admin.html
--
--  El script es RE-EJECUTABLE: borra todo y lo vuelve a crear desde cero.
--  OJO: si ya tenés datos reales cargados, esto los borra. Usalo solo
--  mientras estamos desarrollando.
-- ==========================================================================


-- ==========================================================================
--  0. LIMPIEZA — borra las tablas si ya existían
-- ==========================================================================
-- El orden importa: primero las que dependen de otras.
-- CASCADE borra también las relaciones que apuntaban a ellas.

drop table if exists movimientos_tokens cascade;
drop table if exists codigos_canje       cascade;
drop table if exists pedidos             cascade;
drop table if exists promos              cascade;
drop table if exists productos           cascade;
drop table if exists socios              cascade;
drop table if exists configuracion       cascade;


-- ==========================================================================
--  1. CONFIGURACION — parámetros generales del club
-- ==========================================================================
-- Tabla de clave/valor. En vez de tener una columna por cada parámetro
-- (que obligaría a tocar la base cada vez que aparece uno nuevo), guardamos
-- cada parámetro como una fila. Así el admin puede agregar o editar
-- parámetros desde el panel sin que nadie toque SQL nunca más.

create table configuracion (
  id          bigint generated by default as identity primary key,
  clave       text not null unique,   -- identificador interno, ej: "club_nombre"
  valor       text,                   -- el valor, siempre como texto
  descripcion text,                   -- para qué sirve, se muestra en el admin
  created_at  timestamptz not null default now()
);

comment on table configuracion is 'Parámetros generales del club en formato clave/valor.';


-- ==========================================================================
--  2. SOCIOS — los miembros del club
-- ==========================================================================
-- Cada socio tiene su usuario, su contraseña y su SALDO DE TOKENS.
--
-- IMPORTANTE sobre el saldo:
-- El saldo vive acá como un número, y cada cambio queda además registrado
-- en movimientos_tokens. Pensalo como la cuenta bancaria: "saldo_tokens" es
-- el número grande que ves al entrar al homebanking, y movimientos_tokens
-- es el listado de operaciones que explica cómo llegaste a ese número.
--
-- SEGURIDAD (pendiente conocido): la contraseña va en texto plano, igual que
-- en los proyectos anteriores. Anotado en 07_QA_PENDIENTES.md para endurecer
-- más adelante con RLS o una función RPC de login.

create table socios (
  id            bigint generated by default as identity primary key,
  nombre        text not null,
  apellido      text,
  usuario       text not null unique,          -- con esto entra a la app
  password      text not null,                 -- texto plano por ahora
  email         text,
  telefono      text,
  dni           text,
  saldo_tokens  integer not null default 0,    -- tokens enteros, sin decimales
  estado        text not null default 'activo',-- activo | inactivo | suspendido
  notas         text,                          -- observaciones internas del admin
  created_at    timestamptz not null default now(),

  -- El saldo NUNCA puede quedar negativo. Esta regla la aplica la base:
  -- aunque haya un error en el código de la app, Postgres rechaza la operación.
  constraint saldo_no_negativo check (saldo_tokens >= 0),
  constraint estado_valido      check (estado in ('activo','inactivo','suspendido'))
);

create index idx_socios_usuario on socios (usuario);
create index idx_socios_estado  on socios (estado);

comment on table socios is 'Miembros del club. Incluye credenciales y saldo de tokens.';


-- ==========================================================================
--  3. PRODUCTOS — el catálogo
-- ==========================================================================
-- Todos los precios están EN TOKENS. No hay ninguna columna de plata real
-- en toda la base, a propósito.

create table productos (
  id             bigint generated by default as identity primary key,
  nombre         text not null,
  descripcion    text,
  categoria      text not null,                 -- flores | hash | comestibles | accesorios | merch
  precio_tokens  integer not null,              -- precio en tokens, entero
  stock          integer not null default 0,    -- unidades disponibles
  activo         boolean not null default true, -- false = no se muestra en el catálogo
  imagen_url     text,                          -- opcional, para cuando haya fotos
  orden          integer not null default 0,    -- para ordenar a mano dentro de la categoría
  created_at     timestamptz not null default now(),

  constraint precio_positivo   check (precio_tokens >= 0),
  constraint stock_no_negativo check (stock >= 0)
);

create index idx_productos_categoria on productos (categoria);
create index idx_productos_activo    on productos (activo);

comment on table productos is 'Catálogo de productos. Precios siempre en tokens.';


-- ==========================================================================
--  4. PROMOS — combos y promociones
-- ==========================================================================
-- Todavía no la usa el panel de socios, pero la dejamos creada para que el
-- chat de admin no tenga que rehacer el esquema después.

create table promos (
  id             bigint generated by default as identity primary key,
  nombre         text not null,
  descripcion    text,
  items          jsonb not null default '[]'::jsonb, -- qué productos incluye
  precio_tokens  integer not null,
  activo         boolean not null default true,
  vence_en       timestamptz,                   -- null = no vence
  created_at     timestamptz not null default now(),

  constraint promo_precio_positivo check (precio_tokens >= 0)
);

comment on table promos is 'Combos y promociones. Reservada para el panel de admin.';


-- ==========================================================================
--  5. PEDIDOS — lo que el socio compra
-- ==========================================================================
-- Los items del pedido van adentro de la columna "items", en formato JSON.
--
-- ¿Por qué así y no en una tabla aparte?
-- Pensalo como una caja cerrada: abrís el pedido y adentro está todo lo que
-- pidió. La alternativa sería tener las fichas sueltas en otra tabla y
-- juntarlas cada vez que querés ver un pedido: más llamadas a la base y
-- más código, sin ninguna ventaja para el tamaño de este proyecto.
--
-- Además tiene un beneficio real: guarda el precio CONGELADO al momento de
-- la compra. Si mañana el admin sube el precio de un producto, los pedidos
-- viejos siguen mostrando lo que el socio pagó de verdad.
--
-- Formato esperado de "items":
-- [
--   { "producto_id": 1, "nombre": "Flor Índica", "cantidad": 2, "precio_tokens": 120, "subtotal": 240 },
--   { "producto_id": 7, "nombre": "Brownie",     "cantidad": 1, "precio_tokens": 90,  "subtotal": 90  }
-- ]
--
-- NÚMERO DE PEDIDO: usamos el propio "id". En la app se muestra como
-- #0001, #0002, etc. Así no hay dos fuentes de verdad que se puedan
-- desincronizar.

create table pedidos (
  id            bigint generated by default as identity primary key,
  socio_id      bigint not null references socios(id) on delete cascade,
  socio_nombre  text,                              -- copia del nombre, para que el admin
                                                   -- vea el listado sin cruzar tablas
  items         jsonb not null default '[]'::jsonb,
  total_tokens  integer not null,
  estado        text not null default 'pendiente', -- pendiente | preparando | listo | entregado | cancelado
  nota          text,                              -- comentario opcional del socio
  created_at    timestamptz not null default now(),
  entregado_en  timestamptz,                       -- se completa al marcar entregado
  cancelado_en  timestamptz,

  constraint total_positivo   check (total_tokens >= 0),
  constraint estado_pedido_ok check (estado in ('pendiente','preparando','listo','entregado','cancelado'))
);

create index idx_pedidos_socio  on pedidos (socio_id);
create index idx_pedidos_estado on pedidos (estado);
create index idx_pedidos_fecha  on pedidos (created_at desc);

comment on table pedidos is 'Pedidos de los socios. Los items van como JSON con el precio congelado.';


-- ==========================================================================
--  6. MOVIMIENTOS_TOKENS — el libro contable
-- ==========================================================================
-- Tabla central del sistema. CADA cambio de saldo, sin excepción, deja
-- una fila acá. Es el extracto bancario del socio.
--
-- Tipos posibles:
--   carga_presencial   → el admin le acreditó tokens en el local        (+)
--   canje_codigo       → el socio canjeó un código en la app            (+)
--   ajuste_admin       → corrección manual del admin                    (+ o -)
--   consumo_pedido     → el socio confirmó un pedido                    (-)
--   devolucion_pedido  → se canceló un pedido y volvieron los tokens    (+)
--
-- La columna "cantidad" lleva el signo: positiva si entra, negativa si sale.
-- Así el historial se suma de arriba a abajo sin lógica extra.
--
-- "saldo_resultante" guarda cómo quedó el saldo después del movimiento.
-- Es redundante a propósito: permite auditar si algún día el saldo y el
-- historial no cuadran, y saber en qué movimiento se rompió.

create table movimientos_tokens (
  id                bigint generated by default as identity primary key,
  socio_id          bigint not null references socios(id) on delete cascade,
  socio_nombre      text,
  tipo              text not null,
  cantidad          integer not null,   -- positiva = entrada, negativa = salida
  saldo_resultante  integer,            -- cómo quedó el saldo tras este movimiento
  referencia        text,               -- texto legible: "Pedido #0012", "Código ABC123"
  referencia_id     bigint,             -- id del pedido o del código, si aplica
  detalle           text,               -- nota libre del admin
  created_at        timestamptz not null default now(),

  constraint tipo_movimiento_ok check (
    tipo in ('carga_presencial','canje_codigo','ajuste_admin','consumo_pedido','devolucion_pedido')
  )
);

create index idx_mov_socio on movimientos_tokens (socio_id);
create index idx_mov_fecha on movimientos_tokens (created_at desc);
create index idx_mov_tipo  on movimientos_tokens (tipo);

comment on table movimientos_tokens is 'Historial completo de tokens. Cada carga y cada consumo queda acá.';


-- ==========================================================================
--  7. CODIGOS_CANJE — carga de tokens a distancia
-- ==========================================================================
-- El admin genera un código, se lo pasa al socio por donde sea, y el socio
-- lo canjea en la app. Es la única forma en que un socio suma tokens sin
-- estar presente. UN CÓDIGO SE USA UNA SOLA VEZ.
--
-- La garantía de "una sola vez" la da la base con "usado = true" más la
-- restricción unique del código. La app además verifica antes de acreditar.

create table codigos_canje (
  id            bigint generated by default as identity primary key,
  codigo        text not null unique,           -- lo que el socio escribe en la app
  tokens        integer not null,               -- cuántos tokens acredita
  usado         boolean not null default false,
  usado_por     bigint references socios(id) on delete set null,
  usado_en      timestamptz,
  vence_en      timestamptz,                    -- null = no vence
  descripcion   text,                           -- para qué se generó, lo ve el admin
  created_at    timestamptz not null default now(),

  constraint tokens_positivos check (tokens > 0)
);

create index idx_codigos_codigo on codigos_canje (codigo);
create index idx_codigos_usado  on codigos_canje (usado);

comment on table codigos_canje is 'Códigos de un solo uso para cargar tokens a distancia.';


-- ==========================================================================
--  8. PERMISOS (RLS)
-- ==========================================================================
-- Supabase pide que cada tabla tenga RLS ("Row Level Security") activado.
--
-- Analogía: RLS es el portero del edificio. Si está apagado, entra cualquiera.
-- Si está prendido, el portero mira una lista para decidir quién pasa.
--
-- POR AHORA lo dejamos prendido pero con la lista abierta: el rol "anon"
-- (el que usa la app con la clave pública) puede hacer todo. Es exactamente
-- el mismo nivel de seguridad que tienen los proyectos anteriores que ya
-- están andando.
--
-- QUEDA COMO PENDIENTE endurecer esto antes de producción real, para que un
-- socio no pueda leer los datos de otro. Va anotado en 07_QA_PENDIENTES.md.

alter table configuracion      enable row level security;
alter table socios             enable row level security;
alter table productos          enable row level security;
alter table promos             enable row level security;
alter table pedidos            enable row level security;
alter table movimientos_tokens enable row level security;
alter table codigos_canje      enable row level security;

create policy "acceso_total_temporal" on configuracion      for all using (true) with check (true);
create policy "acceso_total_temporal" on socios             for all using (true) with check (true);
create policy "acceso_total_temporal" on productos          for all using (true) with check (true);
create policy "acceso_total_temporal" on promos             for all using (true) with check (true);
create policy "acceso_total_temporal" on pedidos            for all using (true) with check (true);
create policy "acceso_total_temporal" on movimientos_tokens for all using (true) with check (true);
create policy "acceso_total_temporal" on codigos_canje      for all using (true) with check (true);


-- ==========================================================================
--  9. DATOS DE EJEMPLO
-- ==========================================================================
-- Los mismos datos que va a tener el modo demo del HTML, para que al pasar
-- a Supabase real la app se vea igual y puedas comparar que todo funciona.
-- ==========================================================================

-- --- Configuración ---------------------------------------------------------
insert into configuracion (clave, valor, descripcion) values
  ('club_nombre',        'CLUB',        'Nombre del club. Cambiar cuando esté definido.'),
  ('club_telefono',      '',            'Teléfono de contacto.'),
  ('club_direccion',     '',            'Dirección del local.'),
  ('valor_token',        '',            'Cuánto vale 1 token. Uso interno del admin, NO se muestra al socio.'),
  ('mensaje_bienvenida', 'Bienvenido',  'Texto que ve el socio al entrar.'),
  ('pedidos_activos',    'true',        'Si es false, el socio no puede confirmar pedidos.');

-- --- Socios de prueba ------------------------------------------------------
-- 1) Saldo alto  → para probar el flujo completo sin trabas
-- 2) Saldo bajo  → para probar el bloqueo por saldo insuficiente
-- 3) Inactivo    → para probar que no puede entrar
insert into socios (nombre, apellido, usuario, password, email, telefono, saldo_tokens, estado) values
  ('Martín',  'Álvarez', 'martin', '1234', 'martin@ejemplo.com',  '11 5555-1111', 850, 'activo'),
  ('Carla',   'Duarte',  'carla',  '1234', 'carla@ejemplo.com',   '11 5555-2222',  60, 'activo'),
  ('Diego',   'Ferrer',  'diego',  '1234', 'diego@ejemplo.com',   '11 5555-3333', 200, 'inactivo');

-- --- Catálogo --------------------------------------------------------------
insert into productos (nombre, descripcion, categoria, precio_tokens, stock, activo, orden) values
  -- Flores
  ('Flor Índica',        'Variedad relajante. Efecto corporal, ideal para la noche.', 'flores',      120, 25, true, 1),
  ('Flor Sativa',        'Variedad energizante. Efecto mental, ideal para el día.',   'flores',      120, 18, true, 2),
  ('Flor Híbrida',       'Balance entre efecto corporal y mental.',                   'flores',      130, 12, true, 3),
  ('Flor Premium',       'Selección especial de cultivo interior.',                   'flores',      180,  0, true, 4),
  -- Hash
  ('Hash Tradicional',   'Prensado artesanal, textura maleable.',                     'hash',        200, 10, true, 1),
  ('Hash Premium',       'Extracción en frío, alta pureza.',                          'hash',        320,  5, true, 2),
  -- Comestibles
  ('Brownie',            'Porción individual. Efecto prolongado.',                    'comestibles',  90, 15, true, 1),
  ('Galletitas x3',      'Pack de tres unidades.',                                    'comestibles', 110,  8, true, 2),
  ('Gomitas x10',        'Pack de diez unidades, dosis baja por unidad.',             'comestibles', 150, 20, true, 3),
  ('Aceite 10ml',        'Gotero con dosificador.',                                   'comestibles', 400,  4, true, 4),
  -- Accesorios
  ('Grinder metálico',   'Cuatro partes, con recolector.',                            'accesorios',  160, 12, true, 1),
  ('Papelillos',         'Caja de 50 unidades.',                                      'accesorios',   25, 60, true, 2),
  ('Filtros',            'Pack de 100 unidades.',                                     'accesorios',   20, 45, true, 3),
  ('Bandeja',            'Bandeja metálica mediana.',                                 'accesorios',   90,  7, true, 4),
  -- Merch
  ('Remera del club',    'Algodón, talles S al XL.',                                  'merch',       350,  9, true, 1),
  ('Gorra',              'Bordado frontal.',                                          'merch',       280,  6, true, 2),
  ('Buzo',               'Con capucha, talles S al XL.',                              'merch',       600,  0, true, 3),
  ('Sticker pack',       'Set de seis stickers.',                                     'merch',        40, 30, true, 4);

-- --- Pedidos de ejemplo ----------------------------------------------------
-- Distintos estados para que el historial del socio se vea completo.
insert into pedidos (socio_id, socio_nombre, items, total_tokens, estado, created_at, entregado_en) values
  (1, 'Martín Álvarez',
   '[{"producto_id":1,"nombre":"Flor Índica","cantidad":2,"precio_tokens":120,"subtotal":240},
     {"producto_id":12,"nombre":"Papelillos","cantidad":1,"precio_tokens":25,"subtotal":25}]'::jsonb,
   265, 'entregado', now() - interval '12 days', now() - interval '11 days'),

  (1, 'Martín Álvarez',
   '[{"producto_id":7,"nombre":"Brownie","cantidad":3,"precio_tokens":90,"subtotal":270}]'::jsonb,
   270, 'listo', now() - interval '2 days', null),

  (1, 'Martín Álvarez',
   '[{"producto_id":11,"nombre":"Grinder metálico","cantidad":1,"precio_tokens":160,"subtotal":160}]'::jsonb,
   160, 'pendiente', now() - interval '4 hours', null),

  (2, 'Carla Duarte',
   '[{"producto_id":13,"nombre":"Filtros","cantidad":2,"precio_tokens":20,"subtotal":40}]'::jsonb,
   40, 'preparando', now() - interval '1 day', null);

-- --- Movimientos de tokens -------------------------------------------------
-- Reconstruyen cómo llegó cada socio a su saldo actual.
-- Martín:  500 + 300 - 265 + 745 - 270 - 160 =  850
-- Carla:   100 - 40                          =   60
-- Diego:   200                               =  200
insert into movimientos_tokens (socio_id, socio_nombre, tipo, cantidad, saldo_resultante, referencia, referencia_id, created_at) values
  (1, 'Martín Álvarez', 'carga_presencial',  500,  500, 'Carga en el local', null, now() - interval '20 days'),
  (1, 'Martín Álvarez', 'canje_codigo',      300,  800, 'Código BIENVENIDO', null, now() - interval '15 days'),
  (1, 'Martín Álvarez', 'consumo_pedido',   -265,  535, 'Pedido #0001',         1, now() - interval '12 days'),
  (1, 'Martín Álvarez', 'carga_presencial',  745, 1280, 'Carga en el local', null, now() - interval '5 days'),
  (1, 'Martín Álvarez', 'consumo_pedido',   -270, 1010, 'Pedido #0002',         2, now() - interval '2 days'),
  (1, 'Martín Álvarez', 'consumo_pedido',   -160,  850, 'Pedido #0003',         3, now() - interval '4 hours'),

  (2, 'Carla Duarte',   'carga_presencial',  100,  100, 'Carga en el local', null, now() - interval '6 days'),
  (2, 'Carla Duarte',   'consumo_pedido',    -40,   60, 'Pedido #0004',         4, now() - interval '1 day'),

  (3, 'Diego Ferrer',   'carga_presencial',  200,  200, 'Carga en el local', null, now() - interval '30 days');

-- --- Códigos de canje ------------------------------------------------------
-- Los dos primeros están libres para probar el canje en la app.
-- El tercero ya está usado, para probar el aviso de "código ya utilizado".
insert into codigos_canje (codigo, tokens, usado, usado_por, usado_en, descripcion) values
  ('PRUEBA100',   100, false, null, null,                       'Código de prueba'),
  ('VERANO250',   250, false, null, null,                       'Promo de temporada'),
  ('BIENVENIDO',  300, true,  1,    now() - interval '15 days', 'Bienvenida — ya usado');


-- ==========================================================================
--  10. VERIFICACIÓN
-- ==========================================================================
-- Al terminar deberías ver: 6 config, 3 socios, 18 productos, 4 pedidos,
-- 9 movimientos y 3 códigos.

select 'configuracion'      as tabla, count(*) from configuracion
union all select 'socios',             count(*) from socios
union all select 'productos',          count(*) from productos
union all select 'pedidos',            count(*) from pedidos
union all select 'movimientos_tokens', count(*) from movimientos_tokens
union all select 'codigos_canje',      count(*) from codigos_canje
union all select 'promos',             count(*) from promos;


-- ==========================================================================
--  FIN
-- ==========================================================================
