-- ==========================================================================
--  04_SQL_ADMIN_V3.sql — CAMBIOS PARA admin.html v3
--  Correr DESPUÉS de 03_ESQUEMA_BD.sql, en el SQL Editor de Supabase.
--
--  POR QUÉ EXISTE ESTE ARCHIVO
--  El panel de administración v3 cambió tres cosas que la base todavía no
--  tiene. Sin estos cambios el panel no arranca: el login no encuentra su
--  tabla y los descuentos en el mostrador los rechaza Postgres.
--
--  Es SEGURO de re-ejecutar: no borra datos existentes.
-- ==========================================================================


-- ==========================================================================
--  1. USUARIOS_PANEL — quiénes entran al panel y con qué permisos
-- ==========================================================================
-- Antes había UNA contraseña para todo el panel, guardada como una fila en
-- "configuracion". Ahora hay varias personas, cada una con su usuario, su
-- clave y un rol.
--
-- Analogía: antes el local tenía una sola llave que abría todo y circulaba
-- entre todos. Ahora cada persona tiene la suya, y la llave del empleado no
-- abre las mismas puertas que la del administrador.
--
-- Dos roles:
--   administrador → todo
--   empleado      → cargar tokens, atender pedidos, editar socios.
--                   No ve contabilidad, ni catálogo, ni códigos de canje,
--                   ni puede cancelar pedidos o dar de baja socios.

create table if not exists usuarios_panel (
  id         bigint generated by default as identity primary key,
  usuario    text not null unique,          -- con esto entra al panel
  password   text not null,                 -- texto plano por ahora (ver 07_QA)
  nombre     text not null,                 -- se muestra en pantalla y firma los movimientos
  rol        text not null default 'empleado',
  activo     boolean not null default true, -- false = no puede entrar
  created_at timestamptz not null default now(),

  constraint rol_valido check (rol in ('administrador','empleado'))
);

create index if not exists idx_usuarios_panel_usuario on usuarios_panel (usuario);
create index if not exists idx_usuarios_panel_activo  on usuarios_panel (activo);

comment on table usuarios_panel is 'Usuarios del panel de administración, con rol y estado.';

-- Mismo criterio que el resto de las tablas: RLS prendida, política abierta
-- por ahora. Endurecer antes de producción real (ver 08_BRIEF_SEGURIDAD.md).
alter table usuarios_panel enable row level security;

drop policy if exists "acceso_total_temporal" on usuarios_panel;
create policy "acceso_total_temporal" on usuarios_panel for all using (true) with check (true);


-- ==========================================================================
--  2. HECHO_POR — quién hizo cada movimiento de tokens
-- ==========================================================================
-- Hasta ahora el historial decía QUÉ pasó pero no QUIÉN lo hizo. Con varias
-- personas operando el mostrador eso deja de ser un detalle.
--
-- Guarda el NOMBRE de la persona, no su id: si mañana se borra el usuario,
-- el movimiento viejo sigue diciendo quién lo hizo. La contabilidad no se
-- puede quedar sin firma porque alguien dejó de trabajar en el club.

alter table movimientos_tokens add column if not exists hecho_por text;

comment on column movimientos_tokens.hecho_por is 'Nombre de la persona del panel que registró el movimiento.';


-- ==========================================================================
--  3. CONSUMO_LOCAL — lo que el socio se lleva del mostrador
-- ==========================================================================
-- Tipo de movimiento nuevo: el socio retira algo en el local sin pasar por
-- el carrito de la app. Se descuenta a mano desde el panel.
--
-- OJO, ESTE ES EL PASO CRÍTICO: la restricción actual solo acepta cinco
-- tipos. Si no se amplía, Postgres RECHAZA cada descuento en el mostrador
-- y el panel muestra un error genérico, difícil de diagnosticar.

alter table movimientos_tokens drop constraint if exists tipo_movimiento_ok;

alter table movimientos_tokens add constraint tipo_movimiento_ok check (
  tipo in (
    'carga_presencial',
    'canje_codigo',
    'ajuste_admin',
    'consumo_pedido',
    'devolucion_pedido',
    'consumo_local'      -- <— el nuevo
  )
);


-- ==========================================================================
--  4. USUARIO INICIAL DEL PANEL
-- ==========================================================================
-- Uno solo, administrador, para poder entrar la primera vez.
-- LA CONTRASEÑA ES PROVISORIA: cambiala apenas entres, desde
-- Usuarios del panel. Está anotado en 07_QA_PENDIENTES.

insert into usuarios_panel (usuario, password, nombre, rol, activo) values
  ('sebastian', 'admin', 'Sebastián', 'administrador', true)
on conflict (usuario) do nothing;


-- ==========================================================================
--  5. NOMBRE DEL CLUB
-- ==========================================================================
-- Los dos paneles leen este valor. Estaba en 'CLUB' desde el arranque.

update configuracion
   set valor = 'HOUSE OF AFICIONADO'
 where clave = 'club_nombre';


-- ==========================================================================
--  6. LA FILA admin_password QUEDÓ OBSOLETA
-- ==========================================================================
-- El panel v3 ya no la lee. No la borramos: la marcamos, para que quede
-- claro que no se usa y para no perder el dato si hiciera falta volver atrás.

update configuracion
   set descripcion = 'OBSOLETO desde admin v3 — el login ahora usa la tabla usuarios_panel. Esta fila no se usa.'
 where clave = 'admin_password';


-- ==========================================================================
--  7. VERIFICACIÓN
-- ==========================================================================
select 'usuarios del panel'      as control, count(*)::text as valor from usuarios_panel
union all
select 'columna hecho_por existe',
       (select count(*)::text from information_schema.columns
         where table_name='movimientos_tokens' and column_name='hecho_por')
union all
select 'consumo_local permitido',
       (select case when pg_get_constraintdef(oid) like '%consumo_local%' then 'si' else 'NO' end
          from pg_constraint where conname='tipo_movimiento_ok')
union all
select 'nombre del club', (select valor from configuracion where clave='club_nombre')
union all
select 'RLS en usuarios_panel',
       (select case when rowsecurity then 'si' else 'NO' end
          from pg_tables where schemaname='public' and tablename='usuarios_panel');
